"""Seed data extracted from the spreadsheet's 'Cadastro_ROV' tab."""

# (vessel_name, contractor)
VESSELS = [
    ("Cabo Frio", "Karoon"),
    ("Olin Conqueror", "Petrobras"),
    ("Laney Chouest", "MotaEngil"),
    ("Bram Titan", "Petrobras"),
    ("Wildebeest", "Petrobras"),
    ("Bram Atlas", "Petrobras"),
    ("Joe Griffin", "Petrobras"),
    ("Paulo Cunha", "Petrobras"),
    ("Navegantes Pride", "MotaEngil"),
    ("Santos Solution", "MotaEngil"),
    ("Bushbuck", "BRAVA"),
    ("Santos Service", "Petrobras"),
    ("Debora Kay", "Petrobras"),
    ("Bram Force", "Petrobras"),
    ("Island Enforcer", "Shell"),
    ("Island Intervention", "Equinor"),
    ("Bram Spirit", "Petrobras"),
    ("Bongo", "Petrobras"),
    ("Eland", "Petrobras"),
    ("Bram Bravo", "Petrobras"),
    ("Normand Poseidon", "Petrobras"),
    ("Kirt Chouest", "MotaEngil"),
]

# (rov_id, rov_num, vessel_name, kind)
ROVS = [
    ("UHD32", 32, "Cabo Frio", "UHD"),
    ("Survey32", 32, "Cabo Frio", "SURVEY"),
    ("UHD43", 43, "Olin Conqueror", "UHD"),
    ("Survey43", 43, "Olin Conqueror", "SURVEY"),
    ("UHD45", 45, "Laney Chouest", "UHD"),
    ("Survey45", 45, "Laney Chouest", "SURVEY"),
    ("UHD70", 70, "Bram Titan", "UHD"),
    ("Survey70", 70, "Bram Titan", "SURVEY"),
    ("UHD77", 77, "Wildebeest", "UHD"),
    ("Survey77", 77, "Wildebeest", "SURVEY"),
    ("UHD85", 85, "Bram Atlas", "UHD"),
    ("Survey85", 85, "Bram Atlas", "SURVEY"),
    ("UHD96", 96, "Joe Griffin", "UHD"),
    ("Survey96", 96, "Joe Griffin", "SURVEY"),
    ("UHD105", 105, "Paulo Cunha", "UHD"),
    ("Survey105", 105, "Paulo Cunha", "SURVEY"),
    ("UHD106", 106, "Navegantes Pride", "UHD"),
    ("Survey106", 106, "Navegantes Pride", "SURVEY"),
    ("UHD107", 107, "Santos Solution", "UHD"),
    ("Survey107", 107, "Santos Solution", "SURVEY"),
    ("UHD108", 108, "Bushbuck", "UHD"),
    ("Survey108", 108, "Bushbuck", "SURVEY"),
    ("UHD301", 301, "Santos Service", "UHD"),
    ("Survey301", 301, "Santos Service", "SURVEY"),
    ("UHD314", 314, "Debora Kay", "UHD"),
    ("Survey314", 314, "Debora Kay", "SURVEY"),
    ("UHD53", 53, "Bram Force", "UHD"),
    ("Survey53", 53, "Bram Force", "SURVEY"),
    ("UHD5152", 5152, "Island Enforcer", "UHD"),
    ("Survey5152", 5152, "Island Enforcer", "SURVEY"),
    ("UHD5982", 5982, "Island Intervention", "UHD"),
    ("Survey5982", 5982, "Island Intervention", "SURVEY"),
    ("UHD6869", 6869, "Bram Spirit", "UHD"),
    ("Survey6869", 6869, "Bram Spirit", "SURVEY"),
    ("UHD7374", 7374, "Bongo", "UHD"),
    ("Survey7374", 7374, "Bongo", "SURVEY"),
    ("UHD43100", 43100, "Eland", "UHD"),
    ("Survey43100", 43100, "Eland", "SURVEY"),
    ("UHD47104", 47104, "Bram Bravo", "UHD"),
    ("Survey47104", 47104, "Bram Bravo", "SURVEY"),
    ("UHD99101", 99101, "Normand Poseidon", "UHD"),
    ("Survey99101", 99101, "Normand Poseidon", "SURVEY"),
    ("UHD302322", 302322, "Kirt Chouest", "UHD"),
    ("Survey302322", 302322, "Kirt Chouest", "SURVEY"),
]
